services:
  db:
    image: ysql:8.0.41
    container_name: <container_name>
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: <db_name>
    ports:
      - "<port>:3306"
    volumes:
      - <container_name>:/var/lib/mysql
   
  redis-cache:
    image: redis:alpine
    container_name: <container_name>
    restart: always
    ports:
      - "6379:6379"
 
volumes:
  dotnetmysqldb: